use Mint as dep manager for build tools

diff --git a/project.yml b/project.yml
--- a/project.yml
+++ b/project.yml
@@ -18,6 +18,9 @@ fileGroups:
   - .swiftlint.yml
   - project.yml
   - Dangerfile.swift
+  - Makefile
+  - Mintfile
+  - .github/
 
 targets:
   App:
@@ -28,12 +31,14 @@ targets:
       - Sample/
     postBuildScripts:
       - script: |
-                if which swiftlint >/dev/null; then
-                  swiftlint autocorrect --format
-                  swiftlint
+                if which mint >/dev/null; then
+                  xcrun --sdk macosx mint run swiftlint autocorrect --format
+                  xcrun --sdk macosx mint run swiftlint
                 else
-                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
+                  echo "error: Mint not installed, run `make mint`"
+                  exit 1
                 fi
+
     dependencies:
         - package: OHHTTPStubs
           product: OHHTTPStubsSwift
